name: Docker

on:
  push:              # 每次 push 都触发
    branches:
      - "**"
  workflow_dispatch: # 支持手动触发

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Read version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Checkout biliup repo at tag
        uses: actions/checkout@v3
        with:
          repository: biliup/biliup
          ref: ${{ steps.get_version.outputs.version }}
          path: biliup

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./biliup
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            buyfakett/biliup:${{ steps.get_version.outputs.version }}
